version: "3.8"

services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cex-db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
