version: "3.8"

services:
  postgres:
    image: timescale/timescaledb-ha:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cex-db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
